### model
model_name_or_path: /cluster_home/custom_data/models/Qwen2.5-VL-3B-Instruct  #///
#/home/users/hongyuan.tao/LinearVLMWrapper/weights/Qwen2-VL-2B-Instruct
#/home/users/hongyuan.tao/LinearVLMWrapper/weights/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: dt
do_train: true
finetuning_type: customize
lora_rank: 8
lora_target: all

### dataset
dataset: VLM-SFT-IMG, VLM-SFT-LAG # video: mllm_video_demo  #///
template: qwen2_vl
cutoff_len: 8096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /job_data/1000k_lr2e-4_wd1e-2_newloss
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
tokenized_path: saves/1000K_VLM_SFT

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
weight_decay: 0.01
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## finetune
mixer: Mamba2
mse_factor: 1000
distill_temperature: 2
checkpoint_path: /cluster_home/plat_gpu/linear-20250411-141244.741954/output/1000k_lr5e-4_wd5e-2/stage1/checkpoint-24494
distill_stage: stage2
mixer_config:                             #Used for configuring some processing details within Mamba2 (whether to use residuals, QKNorm, and convolution).
    use_D: false
    use_qknorm: false
    use_short_conv: true 
    use_gnorm: true
    use_A: true
    mimic_init: true
distill_weights: ["g_proj", 
                  "in_proj", 
                  "conv",
                  "D",
                  "g_norm",
                  "q_proj",
                  "k_proj",
                  "v_proj",]
softmax_attention: []  #train mmMamba-linear


### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
